### ISSUE TITLE
Create Internal Interfaces?

### ISSUE THREAD

**Issue by Haukinger** [spadger/simple-config#12]
This works fine with internal classes, but when I try to use an internal interface as settings container, I get `Type 'SimpleConfig.Dynamic.InterfaceImplementations._MyAssembly.IServiceSettings_Impl' from assembly 'SimpleConfig.Dynamic.InterfaceImplementations, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is attempting to implement an inaccessible interface.`

I've tried to make my `InternalsVisibleTo` "SimpleConfig", but that doesn't help. Any idea?

**Comment by Haukinger** [comment]
Figured it out: internals have to be visible to `SimpleConfig.Dynamic.InterfaceImplementations`

But the dynamic creation of implementations does not seem to apply to properties within the interface, i.e. those remain `null`, even if decorated with `CustomEnumerable`.

**Comment by Haukinger** [comment]
Sorted this one out, too: `GetCustomAttributes(true)` does _not_ returned attributes declared in or on implemented interfaces, so `PropertyHelper.GetMappingStrategies` needs to manually look through all implemented interfaces:

To do that, I added `.Concat( @this.DeclaringType.GetInterfaces().SelectMany( x => x.GetProperties().Where( y => y.Name == @this.Name ).SelectMany( y => y.GetMappingStrategies() ) ) )` between `Where` and `ToArray` at the beginning of the method.

**Comment by spadger** [comment]
Good to see you got around this.  TBH though, I'd be inclined to use POCOs instead of interfaces - the interface stuff was really a bad excuse to play with codegen.

POCOs are easier to reason with and control IMHO, and easier to test without mocking config.

**Comment by Haukinger** [comment]
I prefer the interfaces, because they work without setters on the properties. With pocos, technically anybody can modify the settings.

**Comment by spadger** [comment]
I believe your Poco could be

```c#
public class SomeConfig
{
    public string SomeValue { get; private set }
}
```

And obviously it's a valid defensive position to make, but conversely (it took me a number of years to reach this point), do you rate your colleagues so low that they'd be modifying a config instance after initialisation? Possible, but not probable

**Comment by Haukinger** [comment]
It works with a private setter, just not for read-only properties. You might add the line to `GetMappingStrategies` just for completeness' sake, in case someone tries an interface property in an interface.

As for the colleagues... they'll do anything you can or cannot imaging, so I prefer to be safe than sorry :-D

**Comment by spadger** [comment]
Ok.

Read-only properties don't have a setter at all, I believe (I moved over to
java a year ago, so my c# is a little rusty). I'll take a look at your
suggestion, and make changes as necessary. Otherwise, PRs with test cases
are always welcome!

**Comment by spadger** [comment]
Hi,

I no longer have access to a windows machine, and getting this stuff up and running in netstandard so I can develop and test it is not trivial (e.g. `TypeGenerator.cs(132, 51): [CS7069] Reference to type 'Assembly' claims it is defined in 'System.Runtime', but it could not be found` after adding back the missing runtime and code-generation packages)

I'm not sure I have the energy to fix this on a mac

**Comment by spadger** [comment]
For completeness, I took a look at this code with Mono, and I'm hesitant to add your addition.  The current code is for a specific property instance that happens to have a name.  Your code will find mapping strategies for any property that has the same name, but a class can have multiple properties with the same name if they're an explicit interface implementation, so the mapping strategies could end up being a superset of the legal strategies
