### ISSUE TITLE
How to use Simple-Config

### ISSUE THREAD

**Issue by fbrum** [spadger/simple-config#6]
I tried to use simple-config but on the dynamic cast of the section I'm having the error:

"<class> does not inherit from 'System.Configuration.IConfigurationSectionHandler"

I'm sure it must be something very easy, but I'm finding difficult to find it.
Isn't there a tutorial of how to use Simple-Config?

Thanks

**Comment by spadger** [comment]
The tutorial is the readme.  I have never come come across that before.  If you are still interested, could you create a minimal project that has the problem, and I'll check it out.  However, it looks like the problem is in your config file.  Each section you register must be in the pattern 

```xml
<section name="someSectionA" type="SimpleConfig.SimpleConfigHandler, SimpleConfig" />
<section name="someSectionB" type="SimpleConfig.SimpleConfigHandler, SimpleConfig" />

...

<someSectionA foo="bar" />
<someSectionB foo="bar" />
```

**Comment by spadger** [comment]
(Sorry for the late reply - github has not been notifying me about issues to this repo)
